export const GET_ALL_STOCK_REQUEST = "GET_ALL_STOCK_REQUEST";
export const GET_ALL_STOCK_SUCCESS = "GET_ALL_STOCK_SUCCESS";
export const GET_ALL_STOCK_FAILURE = "GET_ALL_STOCK_FAILURE";

export const GET_STOCK_ID_REQUEST = "GET_STOCK_ID_REQUEST";
export const GET_STOCK_ID_SUCCESS = "GET_STOCK_ID_SUCCESS";
export const GET_STOCK_ID_FAILURE = "GET_STOCK_ID_FAILURE";

export const ADD_STOCK_REQUEST = "ADD_STOCK_REQUEST";
export const ADD_STOCK_SUCCESS = "ADD_STOCK_SUCCESS";
export const ADD_STOCK_FAILURE = "ADD_STOCK_FAILURE";

export const UPDATE_STOCK_REQUEST = "UPDATE_STOCK_REQUEST";
export const UPDATE_STOCK_SUCCESS = "UPDATE_STOCK_SUCCESS";
export const UPDATE_STOCK_FAILURE = "UPDATE_STOCK_FAILURE";

export const DELETE_STOCK_REQUEST = "DELETE_STOCK_REQUEST";
export const DELETE_STOCK_SUCCESS = "DELETE_STOCK_SUCCESS";
export const DELETE_STOCK_FAILURE = "DELETE_STOCK_FAILURE";

export const GET_ALL_ORDER_REQUEST = "GET_ALL_ORDER_REQUEST";
export const GET_ALL_ORDER_SUCCESS = "GET_ALL_ORDER_SUCCESS";
export const GET_ALL_ORDER_FAILURE = "GET_ALL_ORDER_FAILURE";

export const GET_ORDER_ID_REQUEST = "GET_ORDER_ID_REQUEST";
export const GET_ORDER_ID_SUCCESS = "GET_ORDER_ID_SUCCESS";
export const GET_ORDER_ID_FAILURE = "GET_ORDER_ID_FAILURE";

export const ADD_ORDER_REQUEST = "ADD_ORDER_REQUEST";
export const ADD_ORDER_SUCCESS = "ADD_ORDER_SUCCESS";
export const ADD_ORDER_FAILURE = "ADD_ORDER_FAILURE";

export const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_FAILURE = "DELETE_ORDER_FAILURE";
